// Generated by CoffeeScript 1.3.3

setTimeout(function() {
  var inject;
  inject = function(name, callback) {
    var s;
    s = document.createElement('script');
    s.src = chrome.extension.getURL('js/' + name);
    s.onload = callback || function() {};
    return document.head.appendChild(s);
  };
  inject('renren-markdown.chrome.js');
},1000);
